Update proxmox.md
benphelps/homepage-docs pull request #82
Opened 2023-04-25 11:49 UTC by Mars-Sea

Proxmox informations doesn't show #1406

2023-04-25 14:17 UTC, shamoon commented
Yea, this is why I don't like to maintain this stuff in our docs. This was just updated https://github.com/benphelps/homepage-docs/pull/59

Maybe you and @shalak can figure it out, I don't even have a proxmox setup so I really cant comment

2023-04-25 14:42 UTC, shalak requested changes
A little cleanup suggestions, overall LGTM

If you choose to add the step 11, please remember to increment the subsequent ones ;)

2023-04-25 14:42 UTC, shalak commented on src/pages/en/services/proxmox.md
> +11. Click on the Permissions "folder"
```suggestion
11. Go back to the "Permissions" menu
```

2023-04-25 14:42 UTC, shalak commented on src/pages/en/services/proxmox.md
> +    - API Token: Your API
```suggestion
    - API Token: select the Token ID created in Step 10
```

2023-04-27 20:20 UTC, Sharnobile approved these changes

2023-05-13 20:01 UTC, merged